apiVersion: v1
data:
  vault-agent-config-init.hcl: |
    # Comment this out if running as sidecar instead of initContainer
    exit_after_auth = true

    pid_file = "/etc/vault-token/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "internal-app"
            }
        }

        sink "file" {
            config = {
                path = "/etc/vault-token/vault-token"
            }
        }
    }

    vault {
        address = "http://vault:8200"
    }


  vault-agent-config-container.hcl: |
    exit_after_auth = false

    pid_file = "/etc/vault-token/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "internal-app"
            }
        }

        sink "file" {
            config = {
                path = "/etc/vault-token/vault-token"
            }
        }
    }

    vault {
        address = "http://vault:8200"
    }
        

kind: ConfigMap
metadata:
  name: {{ include "vaultChart.fullname" . }}
  namespace: default