apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vaultChart.fullname" . }}
  labels:
    {{- include "vaultChart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- with .Values.selectorLabels }}
      {{ toYaml . }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.selectorLabels }}
        {{ toYaml . }}
        {{- end }}
    spec:
      {{if .Values.createInitContainer}}
      volumes:
      - name: config-init
        configMap:
          # defaultMode: 420
          items:
            - key: vault-agent-config-init.hcl
              path: vault-agent-config-init.hcl
          name: {{ include "vaultChart.fullname" . }}
      - name: config-container
        configMap:
          # defaultMode: 420
          items:
            - key: vault-agent-config-container.hcl
              path: vault-agent-config-container.hcl
          name: {{ include "vaultChart.fullname" . }}
      - name: shared-data
        emptyDir: {}

      initContainers:
      - args:
          - agent
          - -config=/etc/vault/vault-agent-config-init.hcl
          - -log-level=debug
        env:
          - name: VAULT_ADDR
            value: {{.Values.envVariables.vault_addr_value}}
        image: vault
        name: vault-agent
        # command: ['sh', '-c', 'cp /etc/vault-token/* /etc/secrets/']
        volumeMounts:
          - mountPath: /etc/vault-token/
            name: shared-data
          - mountPath: /etc/vault/
            name: config-init
      {{end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{.Values.serviceAccount.name}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: {{ .Values.deployment.containerPort }}
            periodSeconds: 3
          readinessProbe:
            initialDelaySeconds: 10
            tcpSocket:
              port: {{ .Values.deployment.containerPort }}
            periodSeconds: 3
          {{ if .Values.envVariables}}
          env:
            - name: {{.Values.envVariables.vault_addr_name}}
              value: {{.Values.envVariables.vault_addr_value}}
            - name: {{.Values.envVariables.vault_token_file_path_name}}
              value: {{.Values.envVariables.vault_token_file_path_value}}
            - name: {{.Values.envVariables.authRole_name}}
              value: {{.Values.envVariables.authRole_value}}
          {{end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{if .Values.createInitContainer}}
          volumeMounts:
          - mountPath: /etc/vault-token/
            name: shared-data
          {{end}}
        {{if .Values.createInitContainer}}
        - args:
          - agent
          - -config=/etc/vault/vault-agent-config-container.hcl
          - -log-level=debug
          image: vault
          imagePullPolicy: Always
          name: vault-agent1
          volumeMounts:
            - mountPath: /etc/vault-token/
              name: shared-data
            - mountPath: /etc/vault/
              name: config-container
        {{end}}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
