apiVersion: v1
kind: Service
metadata:
  name: {{ include "vaultChart.fullname" . }}
  labels:
    {{- with .Values.labels }}
    {{ toYaml . }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- with .Values.selectorLabels }}
    {{ toYaml . }}
    {{- end }}
